//! Compile-time theme discovery.
//!
//! Scans `src/layouts/<theme>/` at build time and generates a Rust
//! file (`$OUT_DIR/themes.rs`) that hardcodes `include_str!` /
//! `include_bytes!` calls for every theme found. The generated file
//! exposes three lookups consumed by the binary:
//!
//!   - `layout_for(theme)`  -> Option<&'static str>
//!   - `css_for(theme)`     -> Option<&'static str>
//!   - `fonts_for(theme)`   -> &'static [(&'static str, &'static [u8])]
//!   - `THEMES`             -> &'static [&'static str]
//!
//! A theme is just a directory under `src/layouts/` containing
//! `layout.resume` and `style.css`. Any files under `<theme>/fonts/`
//! are bundled as font assets and emitted relative to that subtree.
//!
//! To add a new theme: create the directory with the two required
//! files (and optionally fonts), recompile. No code changes needed.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let layouts_dir = Path::new(&manifest_dir).join("src").join("layouts");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_file = Path::new(&out_dir).join("themes.rs");

    // Cargo: rerun if anything under src/layouts changes. The
    // top-level marker alone isn't enough because cargo doesn't
    // recurse, so we walk the tree and emit a directive per file.
    println!("cargo:rerun-if-changed=src/layouts");

    let mut themes: Vec<String> = fs::read_dir(&layouts_dir)
        .unwrap_or_else(|e| panic!("read {}: {}", layouts_dir.display(), e))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let path = entry.path();
            if !path.is_dir() {
                return None;
            }
            let name = path.file_name()?.to_str()?.to_string();
            // Require both layout + css. Anything missing one is
            // an in-progress theme and we skip it rather than
            // crashing the build.
            let has_layout = path.join("layout.resume").is_file();
            let has_css = path.join("style.css").is_file();
            if has_layout && has_css {
                Some(name)
            } else {
                None
            }
        })
        .collect();
    themes.sort();

    let mut out = String::new();
    out.push_str("// Generated by build.rs. Do not edit.\n\n");
    out.push_str("pub const THEMES: &[&str] = &[\n");
    for theme in &themes {
        out.push_str(&format!("    {:?},\n", theme));
    }
    out.push_str("];\n\n");

    // layout_for
    out.push_str("pub fn layout_for(theme: &str) -> Option<&'static str> {\n");
    out.push_str("    match theme {\n");
    for theme in &themes {
        let abs = canonicalize_for_include(&layouts_dir.join(theme).join("layout.resume"));
        println!("cargo:rerun-if-changed={}", abs);
        out.push_str(&format!(
            "        {:?} => Some(include_str!({:?})),\n",
            theme, abs,
        ));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n}\n\n");

    // css_for
    out.push_str("pub fn css_for(theme: &str) -> Option<&'static str> {\n");
    out.push_str("    match theme {\n");
    for theme in &themes {
        let abs = canonicalize_for_include(&layouts_dir.join(theme).join("style.css"));
        println!("cargo:rerun-if-changed={}", abs);
        out.push_str(&format!(
            "        {:?} => Some(include_str!({:?})),\n",
            theme, abs,
        ));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n}\n\n");

    // fonts_for: each theme gets a slice of (relative_path, bytes).
    // Relative path is relative to the theme's fonts/ dir so the
    // consumer can drop them into out_dir/fonts/<same path>.
    out.push_str(
        "pub fn fonts_for(theme: &str) -> &'static [(&'static str, &'static [u8])] {\n",
    );
    out.push_str("    match theme {\n");
    for theme in &themes {
        let fonts_dir = layouts_dir.join(theme).join("fonts");
        let mut entries: Vec<(String, String)> = Vec::new();
        if fonts_dir.is_dir() {
            collect_files(&fonts_dir, &fonts_dir, &mut entries);
        }
        if entries.is_empty() {
            continue;
        }
        entries.sort();
        out.push_str(&format!("        {:?} => &[\n", theme));
        for (rel, abs_for_include) in &entries {
            println!("cargo:rerun-if-changed={}", abs_for_include);
            // include_bytes! resolves relative to the file doing the
            // including, which will be the generated themes.rs in
            // OUT_DIR. Use the absolute path so it works regardless
            // of where OUT_DIR lives.
            out.push_str(&format!(
                "            ({:?}, include_bytes!({:?})),\n",
                rel, abs_for_include,
            ));
        }
        out.push_str("        ],\n");
    }
    out.push_str("        _ => &[],\n");
    out.push_str("    }\n}\n");

    fs::write(&out_file, out)
        .unwrap_or_else(|e| panic!("write {}: {}", out_file.display(), e));
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("file under root")
                .to_string_lossy()
                .replace('\\', "/");
            let abs = canonicalize_for_include(&path);
            out.push((rel, abs));
        }
    }
}

fn canonicalize_for_include(p: &Path) -> String {
    // Use the absolute path so include_bytes! in the generated file
    // (which lives in OUT_DIR) can find the asset back in src/.
    let pb: PathBuf = p
        .canonicalize()
        .unwrap_or_else(|_| p.to_path_buf());
    pb.to_string_lossy().replace('\\', "/")
}
